# Generated by Django 2.1.7 on 2019-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('owner', models.CharField(default='???', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('body', models.TextField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
