# Generated by Django 2.1.7 on 2019-07-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('directory', models.CharField(default='recently', max_length=20)),
                ('display', models.CharField(default='visible', max_length=10)),
                ('keyword', models.CharField(max_length=30)),
                ('urls', models.TextField(default=None)),
                ('memo', models.TextField(default='')),
            ],
        ),
    ]
