# Generated by Django 2.1.7 on 2019-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='memo_id',
            field=models.IntegerField(default=1),
        ),
    ]
