# Generated by Django 2.2.4 on 2019-08-08 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 23, 26, 58, 116097), verbose_name='date_published'),
        ),
    ]
