# Generated by Django 2.2.2 on 2019-08-05 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 11, 3, 36, 63555), verbose_name='date_published'),
        ),
    ]
