# Generated by Django 2.1.7 on 2019-07-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0002_memo_memo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='memo_id',
        ),
    ]
