# Generated by Django 2.1.7 on 2019-07-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0002_auto_20190710_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numofDir',
            field=models.IntegerField(default=0),
        ),
    ]
