# Generated by Django 2.1.7 on 2019-07-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0002_auto_20190722_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 16, 30, 31, 33298), verbose_name='date_published'),
        ),
    ]
