# Generated by Django 2.1.7 on 2019-07-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0003_profile_numofdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
