# Generated by Django 2.1.7 on 2019-07-26 16:03

import datetime
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0003_auto_20190725_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 1, 3, 30, 855864), verbose_name='date_published'),
        ),
    ]
