# Generated by Django 2.1.7 on 2019-07-26 16:04

import datetime
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0004_auto_20190727_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 27, 1, 4, 0, 272014), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='tag',
            field=tagging.fields.TagField(blank=True, default='', max_length=255),
        ),
    ]
