# Generated by Django 2.1.7 on 2019-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0004_memo_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='owner',
            field=models.CharField(default='???', max_length=20),
        ),
    ]
