# Generated by Django 2.1.7 on 2019-07-29 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0005_auto_20190727_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='display',
        ),
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 10, 51, 40, 510380), verbose_name='date_published'),
        ),
    ]
