# Generated by Django 2.1.7 on 2019-07-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0005_memo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numofDir',
            field=models.IntegerField(default=1),
        ),
    ]
