# Generated by Django 2.1.7 on 2019-07-29 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0006_auto_20190729_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 10, 52, 37, 845825), verbose_name='date_published'),
        ),
    ]
