# Generated by Django 2.1.7 on 2019-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0006_auto_20190712_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selectedMemo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numofDir',
            field=models.IntegerField(default=0),
        ),
    ]
