# Generated by Django 2.1.7 on 2019-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0007_auto_20190712_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='download',
            field=models.IntegerField(default=0),
        ),
    ]
