# Generated by Django 2.1.7 on 2019-07-17 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0008_memo_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_published'),
            preserve_default=False,
        ),
    ]
