# Generated by Django 2.1.7 on 2019-07-18 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0008_memo_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 22, 46, 44, 291305), verbose_name='date_published'),
        ),
        migrations.AddField(
            model_name='profile',
            name='currentdir',
            field=models.CharField(default='recently', max_length=20),
        ),
    ]
