# Generated by Django 2.1.7 on 2019-07-30 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0008_auto_20190729_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 14, 28, 53, 543443), verbose_name='date_published'),
        ),
    ]
