# Generated by Django 2.1.7 on 2019-07-17 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0009_memo_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 15, 20, 24, 848540), verbose_name='date_published'),
        ),
    ]
