# Generated by Django 2.1.7 on 2019-07-30 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0010_auto_20190730_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 15, 18, 44, 544720), verbose_name='date_published'),
        ),
    ]
