# Generated by Django 2.1.7 on 2019-07-17 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0010_auto_20190717_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currentdir',
            field=models.CharField(default='recently', max_length=20),
        ),
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 17, 22, 51, 35, 281933), verbose_name='date_published'),
        ),
    ]
