# Generated by Django 2.1.7 on 2019-07-18 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0011_auto_20190717_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 9, 29, 33, 248717), verbose_name='date_published'),
        ),
    ]
