# Generated by Django 2.2.3 on 2019-07-21 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0012_auto_20190718_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 16, 43, 36, 163468), verbose_name='date_published'),
        ),
    ]
