# Generated by Django 2.1.7 on 2019-08-01 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0012_auto_20190801_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 10, 42, 47, 47860), verbose_name='date_published'),
        ),
    ]
