# Generated by Django 2.1.7 on 2019-07-22 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmoa', '0013_auto_20190719_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 13, 9, 39, 10762), verbose_name='date_published'),
        ),
    ]
