# Generated by Django 2.2.3 on 2019-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='directory',
            field=models.CharField(default='recently', max_length=20),
        ),
        migrations.AddField(
            model_name='memo',
            name='display',
            field=models.CharField(default='visible', max_length=10),
        ),
        migrations.AlterField(
            model_name='memo',
            name='memo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='memo',
            name='urls',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='memo',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
